<?php

namespace voganu\tornado\frontend\controllers;

use Yii;
use voganu\tornado\models\TorPrihod;
use voganu\tornado\models\TorPrihodSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yeesoft\controllers\admin\BaseController;

/**
 * TorPrihodController implements the CRUD actions for TorPrihod model.
 */
class SpravController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->language = 'ru_RU';
        $this->layout = 'sprav';
    }

    public function actionIndex()
    {
        return $this->render('index', [
        ]);
    }

}
