<?php

namespace voganu\tornado\frontend\controllers;

use Yii;
use voganu\tornado\models\TorPrihod;
use voganu\tornado\models\TorPrihodSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yeesoft\controllers\admin\BaseController;

/**
 * TorPrihodController implements the CRUD actions for TorPrihod model.
 */
class TorprihodController extends BaseController
{
    const CRUD_ID ='torprihod';
    const COOKIES_ID ='torprihod';
    const COOKIES_DATE_ID ='torprihod-date';
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->language = 'ru_RU';
    }

    protected static function getForceReload(){
        return '#'.self::CRUD_ID.'-pjax';
    }
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }
    protected function setCoookies($val){
        $cookies = \Yii::$app->response->cookies;
// add a new cookie to the response to be sent
        $cookies->add(new \yii\web\Cookie([
            'name' => self::COOKIES_ID,
            'value' => $val,
        ]));

    }
    protected function getCoookies(){
        $cookies = \Yii::$app->request->cookies;
        if ($cookies->has(self::COOKIES_ID)){
            return $cookies->getValue(self::COOKIES_ID);
        }
        return [];
    }

    protected function setCoookiesDate($val){
        $cookies = \Yii::$app->response->cookies;
// add a new cookie to the response to be sent
        $cookies->add(new \yii\web\Cookie([
            'name' => self::COOKIES_DATE_ID,
            'value' => $val,
        ]));

    }
    protected function getCoookiesDate(){
        $cookies = \Yii::$app->request->cookies;
        if ($cookies->has(self::COOKIES_DATE_ID)){
            return $cookies->getValue(self::COOKIES_DATE_ID);
        }
        return [];
    }
    /**
     * Lists all TorPrihod models.
     * @return mixed
     */
    public function actionIndex()
    {
        $new = false;
        if  (\Yii::$app->request->isPost) {
            $query = []  ;
            if ($post =\Yii::$app->request->post('prihodDate', null)) {
                $query['TorPrihodSearch'] = ['prihod_date' => $post];
                $this->setCoookies($query);
    //            $this->setCoookiesDate($post);
    //            \Yii::$app->response->format = Response::FORMAT_JSON;
    //            return ['success' => $model->save()];
            } else {
                $query['TorPrihodSearch'] = ['prihod_date' => '01\01\2100'];
                $new = true;
            }
        }
        else {
            $query = \Yii::$app->request->queryParams;
            if (empty($query)){
                $query = $this->getCoookies();
//
            } else {
                if (!isset($query['TorPrihodSearch'])){
                    $ck = $this->getCoookies();
                    $query = $query + $ck;
                } elseif (isset($query['new'])){
                    $new = true;
                } else {
                    $this->setCoookies($query);
                }


            }
        }
        $currDate = isset($query['TorPrihodSearch']) ? $query['TorPrihodSearch']['prihod_date'] : null;
        $searchModel = new TorPrihodSearch();
        $dataProvider = $searchModel->search($query);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'crudId' => self::CRUD_ID,
            'currDate' => $currDate,
            'new' => $new
        ]);
    }


    /**
     * Displays a single TorPrihod model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Приход",
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Исправить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new TorPrihod model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new TorPrihod();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                $getParams = $request->queryParams;
                if (isset($getParams['currDate'])){
                    $model->prihod_date = (date($getParams['currDate']) > (date('Y')+1)) ? null  : $getParams['currDate']  ;
                }
                return [
                    'title'=> "Новый приход",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post())) {
                try {
                 $model->save();
                $phpdate = strtotime($model->prihod_date);
                $query['TorPrihodSearch'] = ['prihod_date' => date('d/m/Y', $phpdate)];
                $this->setCoookies($query);

                return [
                    'forceReload' => self::getForceReload(),
                    'title' => "Новый приход",
                    'content' => '<span class="text-success">Новый приход сохранен</span>',
                    'footer' => Html::button(
                            'Close',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]
                        ).
                        Html::a('Еще одну', ['create'], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])

                ];
                }catch(\Exception $e){
                    throw new \yii\web\HttpException(405, 'Ошибка сохранения');
                }
            }else{           
                return [
                    'title'=> "Новый пиход",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing TorPrihod model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Изменить",
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>self::getForceReload(),
                    'title'=> "Приход",
                    'content'=>$this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Исправить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
            }else{
                 return [
                    'title'=> "Update TorPrihod #".$id,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing TorPrihod model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>self::getForceReload()];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing TorPrihod model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>self::getForceReload()];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }

    /**
     * Finds the TorPrihod model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TorPrihod the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TorPrihod::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionGroup()
    {
        $query = \Yii::$app->request->queryParams;
        $searchModel = new TorPrihodSearch();
        $dataProvider = $searchModel->search($query);

        return $this->render('indexgroup', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'crudId' => self::CRUD_ID,
        ]);
    }

}
